### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by kubeworkz** [syahidfrd/go-boilerplate#2]
Are you planning to add user signup and JWT auth to your boilerplate?

**Comment by syahidfrd** [comment]
Sure, on progress

**Comment by kubeworkz** [comment]
Great, thanks for the update

**Comment by syahidfrd** [comment]
Here you go!
https://github.com/syahidfrd/go-boilerplate/releases/tag/v2.0.0

**Comment by gridworkz** [comment]
Awesome!!

**Comment by yakupbaser** [comment]
Perfect boilerplate!! Are you planning to add localization?
