### ISSUE TITLE
openapi3 and swaggo

### ISSUE THREAD

**Issue by kubeworkz** [syahidfrd/go-boilerplate#3]
I was able to get swagger docs served via echo server. One question, your jwt stuff uses uid and password for authentication. Is it possible to change to bearer auth tokens for authentication?

**Comment by syahidfrd** [comment]
Hi, to generate a jwt token for authentication, we use a login endpoint with a combination of uid and password as the payload, and to access protected resources we can use the bearer auth token (jwt) that we got earlier
