### ISSUE TITLE
Add graceful Shutdown for High availability service

### ISSUE THREAD

**Issue by alfiankan** [syahidfrd/go-boilerplate#4]
This boilerplate is very helpful for me to create go api projects without starting from scratch,  but it would be nice if we implemented a graceful shutdown for the sake of the user, let's say the user is still in the middle of a request and we need to update our app or maybe our app crashes we can drain the connection first before shutting down.

i was tried to do long live request and send interruption signal then i got an error.

Spoiler :
<img width="476" alt="Screenshot 2023-01-02 at 13 10 12" src="https://user-images.githubusercontent.com/40946917/210199862-63c6d120-a772-47b0-bf09-60fe8c32acf8.png">

My proposal :

adding graceful shitdown using go routine and channel just like in the echo docs https://echo.labstack.com/cookbook/graceful-shutdown/

```go
package main

/* folded code */

func main() {
      
       /* folded code */

       
	// Setup route engine & middleware
	e := echo.New()
	e.Use(middleware.CORS())
	e.Use(appMiddleware.RequestID())
	e.Use(appMiddleware.Logger())
	e.Use(middleware.Recover())

	// Setup handler
	e.GET("/swagger/*", echoSwagger.WrapHandler)
	e.GET("/", func(c echo.Context) error {
		return c.String(http.StatusOK, "i am alive")
	})

	httpDelivery.NewTodoHandler(e, appMiddleware, todoUC)
	httpDelivery.NewAuthHandler(e, appMiddleware, authUC)

       // gracefull shutdown
       	go func() {
		if err := e.Start(fmt.Sprintf(":%s", configApp.ServerPORT)); err != nil && err != http.ErrServerClosed {
			e.Logger.Fatal("shutting down the server")
		}
	}()

        quit := make(chan os.Signal, 1)
	signal.Notify(quit, os.Interrupt)
	<-quit
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := e.Shutdown(ctx); err != nil {
		e.Logger.Fatal(err)
	}

}
```

it would be nice if you assign this issue to me because i'm gabut

**Comment by syahidfrd** [comment]
Hi @alfiankan thanks for your feedback, will be assigned this issue to you, soon!
